import '../../models/workout_model.dart';

class WorkoutData {
  static const String _imgBase =
      'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises';

  static String frame0(String folder) => '$_imgBase/$folder/0.jpg';
  static String frame1(String folder) => '$_imgBase/$folder/1.jpg';

  static final List<MuscleGroup> muscleGroups = [

    MuscleGroup(
      id: 'chest', name: 'Chest', icon: 'strength', color: 0xFFEF5350,
      exercises: [
        Exercise(id: 'push_up', name: 'Push-Up', muscleGroup: 'Chest',
          difficulty: 'Beginner', equipment: 'None', durationSeconds: 60,
          sets: 4, reps: '15-20', gifUrl: 'Pushups',
          description: 'The gold-standard bodyweight pressing movement building chest, shoulders, and triceps with zero equipment.',
          steps: ['Start in a high plank — hands slightly wider than shoulder-width.','Form a straight line from head to heels.','Lower your chest toward the floor, elbows at 45°.','Press forcefully back up to full arm extension.'],
          formCues: ['Do not let hips sag or pike.','Keep neck neutral.','Full range — chest nearly touches the floor.','Breathe in on the way down, out on the way up.'],
          kalories: 7, muscles: ['Pectorals','Triceps','Core'], previewEmoji: ''),
        Exercise(id: 'wide_push_up', name: 'Wide Push-Up', muscleGroup: 'Chest',
          difficulty: 'Beginner', equipment: 'None', durationSeconds: 60,
          sets: 3, reps: '12-15', gifUrl: 'Push-Up_Wide',
          description: 'Wide-grip push-up shifts emphasis to the outer pectorals by placing hands 1.5× shoulder-width apart.',
          steps: ['Place hands 1.5× shoulder-width apart.','Fingers point forward or slightly outward.','Lower chest to floor, elbows wide.','Press back up, squeezing chest at top.'],
          formCues: ['Core rigid — no hip sagging.','Elbows flare at about 75°.','Full range of motion.','Slow descent for extra stimulus.'],
          kalories: 7, muscles: ['Outer Pectorals','Anterior Deltoids','Triceps'], previewEmoji: ''),
        Exercise(id: 'dumbbell_fly', name: 'Dumbbell Fly', muscleGroup: 'Chest',
          difficulty: 'Beginner', equipment: 'Dumbbells', durationSeconds: 0,
          sets: 3, reps: '12-15', gifUrl: 'Dumbbell_Flyes',
          description: 'Isolate the chest through a wide arc of motion, maximising stretch and peak contraction for chest width.',
          steps: ['Lie on bench holding dumbbells above chest, palms facing each other.','Maintain a slight bend in elbows throughout.','Lower dumbbells in a wide arc until deep stretch.','Squeeze chest to bring dumbbells back together.'],
          formCues: ['Consistent elbow bend — never lock out.','Arc motion, not a press.','Lower slowly (3-4 s) for maximum activation.','No momentum — pure isolation.'],
          kalories: 6, muscles: ['Pectorals (Outer)','Anterior Deltoids'], previewEmoji: ''),
        Exercise(id: 'incline_db_press', name: 'Incline Dumbbell Press', muscleGroup: 'Chest',
          difficulty: 'Intermediate', equipment: 'Dumbbells', durationSeconds: 0,
          sets: 4, reps: '10-12', gifUrl: 'Incline_Dumbbell_Press',
          description: 'Targets the upper pectorals at 30-45°, shifting emphasis from mid to upper chest.',
          steps: ['Set bench to 30-45 degrees. Sit back with dumbbells on thighs.','Kick dumbbells to shoulder height as you lie back.','Press up and slightly inward until dumbbells nearly touch.','Lower under control until elbows are just below bench level.'],
          formCues: ['Keep wrists neutral.','30-45° angle only — higher becomes shoulder exercise.','Bring dumbbells together at top for peak contraction.','Lower slowly to feel upper chest stretch.'],
          kalories: 8, muscles: ['Upper Pectorals','Anterior Deltoids','Triceps'], previewEmoji: ''),
        Exercise(id: 'chest_dip', name: 'Chest Dips', muscleGroup: 'Chest',
          difficulty: 'Intermediate', equipment: 'Parallel Bars', durationSeconds: 0,
          sets: 3, reps: '8-12', gifUrl: 'Dips_-_Chest_Version',
          description: 'Compound movement loading the lower pectorals. Leaning forward shifts emphasis from triceps to chest.',
          steps: ['Grip parallel bars and press up to start.','Lean torso forward approximately 30°.','Lower under control until upper arms are parallel to floor.','Push back up forcefully, keeping forward lean.'],
          formCues: ['Forward lean is essential — without it this is a tricep exercise.','Do not dip below parallel.','Elbows flared slightly outward engages chest more.','Cross ankles behind you for stability.'],
          kalories: 8, muscles: ['Lower Pectorals','Anterior Deltoids','Triceps'], previewEmoji: ''),
        Exercise(id: 'decline_push_up', name: 'Decline Push-Up', muscleGroup: 'Chest',
          difficulty: 'Intermediate', equipment: 'None', durationSeconds: 0,
          sets: 3, reps: '10-15', gifUrl: 'Decline_Push-Up',
          description: 'Elevating the feet shifts the push-up angle downward, increasing upper chest activation with zero equipment.',
          steps: ['Place feet on a chair or elevated surface.','Set hands slightly wider than shoulder-width.','Lower chest toward floor, elbows at 45°.','Press back up powerfully to full extension.'],
          formCues: ['Higher feet = more upper chest.','Maintain a straight line from head to hips.','Rigid core at all times.','Full range every rep.'],
          kalories: 7, muscles: ['Upper Pectorals','Anterior Deltoids','Triceps'], previewEmoji: ''),
      ],
    ),

    MuscleGroup(
      id: 'back', name: 'Back', icon: 'back', color: 0xFF42A5F5,
      exercises: [
        Exercise(id: 'pull_up', name: 'Pull-Up', muscleGroup: 'Back',
          difficulty: 'Intermediate', equipment: 'Pull-up Bar', durationSeconds: 0,
          sets: 4, reps: '6-10', gifUrl: 'Pullups',
          description: 'The definitive upper-body pulling exercise, building a wide back and developing biceps as synergists.',
          steps: ['Hang with overhand grip slightly wider than shoulder-width.','Retract shoulder blades and engage core.','Pull chest toward bar, elbows driving down.','Lower slowly to a full dead hang.'],
          formCues: ['No swinging — strict controlled form.','Lead with chest not chin.','Full dead hang at bottom for max lat stretch.','Brace core — do not swing.'],
          kalories: 10, muscles: ['Latissimus Dorsi','Biceps','Rear Deltoids'], previewEmoji: ''),
        Exercise(id: 'chin_up', name: 'Chin-Up', muscleGroup: 'Back',
          difficulty: 'Intermediate', equipment: 'Pull-up Bar', durationSeconds: 0,
          sets: 3, reps: '6-10', gifUrl: 'Chin-Up',
          description: 'Underhand grip recruits the biceps more heavily while still powerfully targeting the latissimus dorsi.',
          steps: ['Hang with underhand (supinated) grip, shoulder-width.','Engage core and retract shoulder blades.','Pull until chin clears bar, elbows toward hips.','Lower to a full dead hang under control.'],
          formCues: ['Supinated grip naturally recruits more bicep.','No swinging — strict form.','Squeeze lats at the top.','Full extension at bottom.'],
          kalories: 9, muscles: ['Latissimus Dorsi','Biceps Brachii','Rear Deltoids'], previewEmoji: ''),
        Exercise(id: 'bent_over_row', name: 'Bent-Over Row', muscleGroup: 'Back',
          difficulty: 'Intermediate', equipment: 'Barbell', durationSeconds: 0,
          sets: 4, reps: '8-10', gifUrl: 'Bent_Over_Barbell_Row',
          description: 'Builds thickness and strength in the upper and mid-back, targeting rhomboids, traps, and rear deltoids.',
          steps: ['Feet shoulder-width, barbell with overhand grip.','Hinge at hips 30-45° from horizontal, knees slightly bent.','Row bar toward lower chest, elbows close.','Hold squeeze at top 1 second, lower with control.'],
          formCues: ['Neutral spine throughout.','Lead pull with elbows not biceps.','Bar stays close to body.','Do not use lower back to jerk the weight.'],
          kalories: 9, muscles: ['Rhomboids','Traps','Rear Deltoids','Biceps'], previewEmoji: ''),
        Exercise(id: 'inverted_row', name: 'Inverted Row', muscleGroup: 'Back',
          difficulty: 'Beginner', equipment: 'Pull-up Bar', durationSeconds: 0,
          sets: 3, reps: '10-15', gifUrl: 'Inverted_Row',
          description: 'Bodyweight horizontal pulling exercise training mid-back, rhomboids, and biceps. Foot position controls difficulty.',
          steps: ['Set bar at waist height. Hang beneath with overhand grip.','Keep body in a straight plank line.','Pull chest up to bar, elbows driving toward hips.','Lower slowly back to full arm extension.'],
          formCues: ['More horizontal body = harder.','Squeeze shoulder blades at top.','Do not let hips sag.','Control the descent.'],
          kalories: 7, muscles: ['Rhomboids','Middle Traps','Rear Deltoids','Biceps'], previewEmoji: ''),
        Exercise(id: 'rear_delt_fly', name: 'Rear Delt Fly', muscleGroup: 'Back',
          difficulty: 'Beginner', equipment: 'Dumbbells', durationSeconds: 0,
          sets: 3, reps: '15-20', gifUrl: 'Bent_Over_Dumbbell_Rear_Delt_Raise_With_Head_On_Bench',
          description: 'Targets the posterior deltoid and rhomboids — critical for posture and shoulder health.',
          steps: ['Hinge forward at hips until torso nearly parallel to floor.','Hold dumbbells below chest, palms facing each other.','Raise dumbbells out to sides until arms are parallel to floor.','Lead with elbows. Lower under control.'],
          formCues: ['Neutral spine throughout.','Slow and controlled.','Lead with elbows, like wings spreading.','Avoid shrugging traps.'],
          kalories: 4, muscles: ['Posterior Deltoids','Rhomboids','Middle Traps'], previewEmoji: ''),
        Exercise(id: 'superman_back', name: 'Superman Hold', muscleGroup: 'Back',
          difficulty: 'Beginner', equipment: 'None', durationSeconds: 40,
          sets: 3, reps: '10-15 (3 s hold)', gifUrl: 'Superman',
          description: 'Floor-based lower back isolation targeting erector spinae through extension — ideal for beginners.',
          steps: ['Lie face-down, arms extended in front, legs straight.','Simultaneously lift arms, chest, and legs off floor.','Hold for 3 seconds, squeezing glutes and lower back.','Lower everything back to the floor.'],
          formCues: ['Squeeze glutes — protects lumbar spine.','Look at the floor.','Lift as high as comfortable.','Breathe steadily through the hold.'],
          kalories: 4, muscles: ['Erector Spinae','Rhomboids','Posterior Deltoid'], previewEmoji: ''),
      ],
    ),

    MuscleGroup(
      id: 'shoulders', name: 'Shoulders', icon: 'shoulders', color: 0xFFAB47BC,
      exercises: [
        Exercise(id: 'overhead_press', name: 'Overhead Press', muscleGroup: 'Shoulders',
          difficulty: 'Intermediate', equipment: 'Barbell', durationSeconds: 0,
          sets: 4, reps: '8-10', gifUrl: 'Barbell_Shoulder_Press',
          description: 'Premier compound shoulder exercise building size and strength in all three deltoid heads.',
          steps: ['Bar on front deltoids, gripped just outside shoulder width.','Brace core and squeeze glutes before pressing.','Press bar straight overhead until arms fully locked out.','Lower back to clavicles with control.'],
          formCues: ['Brace core tightly.','Bar travels in a straight vertical line.','Tuck chin slightly as bar passes face.','Lock out elbows fully at top.'],
          kalories: 9, muscles: ['Anterior Deltoids','Medial Deltoids','Triceps','Upper Traps'], previewEmoji: ''),
        Exercise(id: 'lateral_raise', name: 'Lateral Raise', muscleGroup: 'Shoulders',
          difficulty: 'Beginner', equipment: 'Dumbbells', durationSeconds: 0,
          sets: 3, reps: '12-15', gifUrl: 'Side_Lateral_Raise',
          description: 'The defining exercise for medial deltoid — the head responsible for shoulder width and the "capped" appearance.',
          steps: ['Stand upright, light dumbbells at sides, palms inward.','Raise dumbbells out to sides with slight elbow bend.','Stop when arms reach shoulder height.','Tilt pinky slightly higher than thumb at top. Lower under control.'],
          formCues: ['Lead with elbows not hands.','Pinky-up rotation is key.','Strict form, lighter weight.','Avoid shrugging — traps relaxed.'],
          kalories: 4, muscles: ['Medial Deltoids','Supraspinatus'], previewEmoji: ''),
        Exercise(id: 'arnold_press', name: 'Arnold Press', muscleGroup: 'Shoulders',
          difficulty: 'Intermediate', equipment: 'Dumbbells', durationSeconds: 0,
          sets: 3, reps: '10-12', gifUrl: 'Arnold_Dumbbell_Press',
          description: 'Adds a rotational component to the standard press, activating all three deltoid heads across the full range.',
          steps: ['Sit upright, dumbbells in front of face, palms toward you.','Press upward, rotating palms outward to face forward at top.','Lock out fully overhead.','Reverse rotation as you lower back to start.'],
          formCues: ['Smooth controlled rotation.','Firm back support for lower spine safety.','Full rotation is what makes this unique.','Controlled tempo: 2 s up, 2 s down.'],
          kalories: 7, muscles: ['Anterior Deltoids','Medial Deltoids','Posterior Deltoids','Triceps'], previewEmoji: ''),
        Exercise(id: 'front_raise', name: 'Front Raise', muscleGroup: 'Shoulders',
          difficulty: 'Beginner', equipment: 'Dumbbells', durationSeconds: 0,
          sets: 3, reps: '12-15', gifUrl: 'Front_Incline_Dumbbell_Raise',
          description: 'Isolates the anterior deltoid. Best used as a finishing movement with moderate weight.',
          steps: ['Stand upright, dumbbells in front of thighs, palms toward body.','Raise dumbbells directly in front with almost straight elbows.','Stop at shoulder height. Hold 1 second.','Lower slowly.'],
          formCues: ['Do not swing torso.','Slight elbow bend to protect joint.','Stop at shoulder height.','Alternate or both together.'],
          kalories: 4, muscles: ['Anterior Deltoids','Upper Pectorals'], previewEmoji: ''),
        Exercise(id: 'pike_push_up', name: 'Pike Push-Up', muscleGroup: 'Shoulders',
          difficulty: 'Intermediate', equipment: 'None', durationSeconds: 0,
          sets: 3, reps: '8-12', gifUrl: 'Handstand_Push-Ups',
          description: 'Targets shoulders through a vertical pressing pattern — the bodyweight alternative to the overhead press.',
          steps: ['Start in downward-dog position — hands and feet on floor, hips high.','Walk feet in until body forms an inverted V.','Bend elbows and lower top of head toward floor.','Press back up to starting inverted-V position.'],
          formCues: ['Hips stay high throughout.','Keep core braced.','Straight-arm start position is key.','Feet-elevated version for more difficulty.'],
          kalories: 6, muscles: ['Anterior Deltoids','Medial Deltoids','Triceps'], previewEmoji: ''),
      ],
    ),

    MuscleGroup(
      id: 'legs', name: 'Legs', icon: 'legs', color: 0xFF66BB6A,
      exercises: [
        Exercise(id: 'squat', name: 'Bodyweight Squat', muscleGroup: 'Legs',
          difficulty: 'Beginner', equipment: 'None', durationSeconds: 0,
          sets: 4, reps: '15-20', gifUrl: 'Bodyweight_Squat',
          description: 'The fundamental lower body exercise building quad, glute, and hamstring strength with no equipment.',
          steps: ['Feet shoulder-width, toes 15-30° outward.','Push hips back and knees out to initiate.','Descend until hip crease is below knee.','Drive floor away extending hips and knees to rise.'],
          formCues: ['Chest up, spine neutral.','Knees track over toes.','Hip crease at least parallel to knee.','Brace before descending.'],
          kalories: 7, muscles: ['Quadriceps','Glutes','Hamstrings','Core'], previewEmoji: ''),
        Exercise(id: 'barbell_squat', name: 'Barbell Squat', muscleGroup: 'Legs',
          difficulty: 'Intermediate', equipment: 'Barbell', durationSeconds: 0,
          sets: 4, reps: '8-10', gifUrl: 'Barbell_Full_Squat',
          description: 'The king of lower-body exercises with unmatched hormonal and muscular stimulus.',
          steps: ['Bar on upper traps (high bar) or rear deltoids (low bar).','Feet shoulder-width, toes 15-30° outward.','Big breath, brace core.','Hips back, knees out — descend below parallel.','Drive floor away.'],
          formCues: ['Chest up, spine neutral.','Knees tracking over toes.','Below parallel every rep.','Brace and breathe properly.'],
          kalories: 12, muscles: ['Quadriceps','Glutes','Hamstrings','Core','Adductors'], previewEmoji: ''),
        Exercise(id: 'deadlift', name: 'Deadlift', muscleGroup: 'Legs',
          difficulty: 'Advanced', equipment: 'Barbell', durationSeconds: 0,
          sets: 4, reps: '5-6', gifUrl: 'Barbell_Deadlift',
          description: 'The ultimate test of total body strength, training the entire posterior chain.',
          steps: ['Feet hip-width, bar over mid-foot.','Grip just outside knees — double overhand or mixed.','Drop hips, chest up, shoulders slightly in front.','Brace hard, push floor away, bar drags shins.','Lock out squeezing glutes at top.'],
          formCues: ['Bar contacts legs the entire pull.','Neutral spine — rounding is dangerous.','Engage lats hard before pulling.','Lock out with hips not by hyperextending back.'],
          kalories: 14, muscles: ['Hamstrings','Glutes','Erector Spinae','Traps','Lats'], previewEmoji: ''),
        Exercise(id: 'lunges', name: 'Walking Lunges', muscleGroup: 'Legs',
          difficulty: 'Beginner', equipment: 'None', durationSeconds: 0,
          sets: 3, reps: '12 each leg', gifUrl: 'Dumbbell_Lunges',
          description: 'Unilateral leg exercise building strength, balance, and coordination while exposing imbalances.',
          steps: ['Stand upright, feet together, hands on hips.','Step forward with one leg, long stride.','Lower back knee toward floor, front shin vertical.','Push through front heel, step forward bringing rear leg through.'],
          formCues: ['Torso upright.','Front knee not past toes.','Full long step.','Core braced throughout.'],
          kalories: 8, muscles: ['Quadriceps','Glutes','Hamstrings','Balance'], previewEmoji: ''),
        Exercise(id: 'romanian_deadlift', name: 'Romanian Deadlift', muscleGroup: 'Legs',
          difficulty: 'Intermediate', equipment: 'Barbell', durationSeconds: 0,
          sets: 3, reps: '10-12', gifUrl: 'Romanian_Deadlift',
          description: 'Premier hamstring-focused exercise. Fixed-knee hinge maximises hamstring stretch and contraction.',
          steps: ['Stand holding barbell, overhand grip, feet hip-width.','Slight knee bend maintained throughout.','Hinge at hips, pushing them backward, bar down thighs.','Lower until strong hamstring stretch just below knee.','Drive hips forward to stand. Squeeze glutes.'],
          formCues: ['Push hips back not knees down.','Bar contacts legs throughout.','Neutral spine always.','Hamstring stretch guides depth.'],
          kalories: 10, muscles: ['Hamstrings','Glutes','Erector Spinae'], previewEmoji: ''),
        Exercise(id: 'jump_squat', name: 'Jump Squat', muscleGroup: 'Legs',
          difficulty: 'Intermediate', equipment: 'None', durationSeconds: 0,
          sets: 3, reps: '10-12', gifUrl: 'Front_Box_Jump',
          description: 'Builds explosive power through plyometric loading, training fast-twitch fibre development.',
          steps: ['Stand feet shoulder-width.','Descend into half squat, arms swing back.','Explode upward, arms swing forward.','Land softly with knees bent to absorb.','Immediately into next rep.'],
          formCues: ['Land softly — loud landings mean too much impact.','Knees track toes on landing.','Half squat depth for safety.','Arms generate momentum.'],
          kalories: 11, muscles: ['Quadriceps','Glutes','Calves','Hamstrings'], previewEmoji: ''),
      ],
    ),

    MuscleGroup(
      id: 'arms', name: 'Arms', icon: 'strength', color: 0xFFFFA726,
      exercises: [
        Exercise(id: 'bicep_curl', name: 'Barbell Bicep Curl', muscleGroup: 'Arms',
          difficulty: 'Beginner', equipment: 'Barbell', durationSeconds: 0,
          sets: 3, reps: '10-12', gifUrl: 'Barbell_Curl',
          description: 'Most effective mass-building bicep exercise, allowing maximum bilateral loading.',
          steps: ['Stand feet shoulder-width, barbell underhand grip.','Pin elbows firmly to sides.','Curl bar to shoulder height by bending elbows only.','Squeeze hard at top 1 second. Lower slowly over 3 seconds.'],
          formCues: ['Do not swing torso.','Elbows pinned — only forearms move.','Squeeze hard at top.','Slow eccentric builds muscle too.'],
          kalories: 5, muscles: ['Biceps Brachii','Brachialis'], previewEmoji: ''),
        Exercise(id: 'tricep_dip', name: 'Tricep Dips', muscleGroup: 'Arms',
          difficulty: 'Intermediate', equipment: 'Parallel Bars', durationSeconds: 0,
          sets: 3, reps: '10-12', gifUrl: 'Dips_-_Triceps_Version',
          description: 'Compound bodyweight movement targeting the triceps. Upright posture maximises tricep recruitment.',
          steps: ['Grip parallel bars, press to starting position, arms extended.','Keep torso upright — maximises tricep recruitment.','Lower bending elbows until upper arms are parallel to floor.','Press explosively back to full extension.'],
          formCues: ['Stay upright — leaning forward shifts to chest.','Do not dip below parallel.','Full lockout at top.','In on descent, out on press.'],
          kalories: 7, muscles: ['Triceps','Lower Chest','Anterior Deltoids'], previewEmoji: ''),
        Exercise(id: 'hammer_curl', name: 'Hammer Curl', muscleGroup: 'Arms',
          difficulty: 'Beginner', equipment: 'Dumbbells', durationSeconds: 0,
          sets: 3, reps: '10-12', gifUrl: 'Hammer_Curls',
          description: 'Neutral grip shifts emphasis to brachialis and brachioradialis, creating a thicker arm.',
          steps: ['Stand, dumbbells neutral grip — thumbs pointing up.','Pin elbows to sides.','Curl to shoulder height, no wrist rotation.','Lower slowly.'],
          formCues: ['Maintain neutral grip throughout.','Elbows stationary.','Also strengthens wrist and forearm.','Alternate or both together.'],
          kalories: 5, muscles: ['Brachialis','Brachioradialis','Biceps Brachii'], previewEmoji: ''),
        Exercise(id: 'skull_crusher', name: 'Skull Crusher', muscleGroup: 'Arms',
          difficulty: 'Intermediate', equipment: 'EZ-Bar', durationSeconds: 0,
          sets: 3, reps: '10-12', gifUrl: 'EZ-Bar_Skullcrusher',
          description: 'Stretches the long head of the triceps — the largest head — for maximum mass building.',
          steps: ['Lie on bench, EZ-bar above chest arms extended.','Bar positioned above forehead.','Lower bar toward forehead bending only at elbows.','Upper arms perfectly vertical throughout.','Extend back to start.'],
          formCues: ['Upper arms must remain vertical.','Slow down near head.','Stretch at bottom is uniquely effective.','EZ-bar reduces wrist stress.'],
          kalories: 6, muscles: ['Triceps (Long Head)','Triceps (Lateral Head)'], previewEmoji: ''),
        Exercise(id: 'diamond_push_up', name: 'Diamond Push-Up', muscleGroup: 'Arms',
          difficulty: 'Intermediate', equipment: 'None', durationSeconds: 0,
          sets: 3, reps: '10-15', gifUrl: 'Push-Ups_-_Close_Triceps_Position',
          description: 'Hands in diamond shape maximally activates the triceps and inner chest with no equipment.',
          steps: ['Plank position, hands forming diamond under chest.','Index fingers and thumbs touching.','Lower chest toward hands, elbows pointing back.','Press up explosively.'],
          formCues: ['Elbows point back toward feet not sideways.','Core rigid, no hip sagging.','Full range of motion.','Slow descent for more time-under-tension.'],
          kalories: 7, muscles: ['Triceps','Inner Pectorals','Anterior Deltoids'], previewEmoji: ''),
        Exercise(id: 'preacher_curl', name: 'Preacher Curl', muscleGroup: 'Arms',
          difficulty: 'Intermediate', equipment: 'EZ-Bar', durationSeconds: 0,
          sets: 3, reps: '10-12', gifUrl: 'Preacher_Curl',
          description: 'Angled pad eliminates momentum and isolates the biceps for better peak and fullness.',
          steps: ['Sit at preacher bench, upper arms flat on angled pad.','Hold EZ-bar or dumbbells underhand grip.','Lower to near full extension feeling the stretch.','Curl to shoulder height, squeeze hard at top.'],
          formCues: ['Upper arms pressed firmly against pad.','Lower fully for full stretch.','Use appropriate weight — no cheating.','Squeeze at top, hold 1 second.'],
          kalories: 5, muscles: ['Biceps Brachii','Brachialis'], previewEmoji: ''),
      ],
    ),

    MuscleGroup(
      id: 'core', name: 'Core', icon: 'core', color: 0xFFEF9A9A,
      exercises: [
        Exercise(id: 'plank', name: 'Plank', muscleGroup: 'Core',
          difficulty: 'Beginner', equipment: 'None', durationSeconds: 60,
          sets: 3, reps: '30-60 sec', gifUrl: 'Plank',
          description: 'Gold-standard isometric core exercise building anti-extension strength.',
          steps: ['Forearm plank — forearms flat, elbows under shoulders.','Press up onto forearms and toes forming straight line.','Brace core as if absorbing a punch. Squeeze glutes.','Hold for prescribed duration breathing steadily.'],
          formCues: ['No hip sagging or piking.','Look at floor, neck neutral.','Squeeze glutes tight.','Push elbows into ground.'],
          kalories: 4, muscles: ['Transverse Abdominis','Rectus Abdominis','Obliques'], previewEmoji: ''),
        Exercise(id: 'crunches', name: 'Bicycle Crunches', muscleGroup: 'Core',
          difficulty: 'Beginner', equipment: 'None', durationSeconds: 45,
          sets: 3, reps: '20 each side', gifUrl: 'Air_Bike',
          description: 'Top-ranked ab exercise in EMG studies simultaneously targeting rectus abdominis and obliques.',
          steps: ['Lie on back, hands behind head, knees at 90°.','Lift shoulders slightly off ground.','Right elbow toward left knee while extending right leg.','Switch in smooth controlled pedalling motion.'],
          formCues: ['Do not pull on neck.','Slow and deliberate.','Rotate torso not just elbows.','Lower back pressed to floor.'],
          kalories: 5, muscles: ['Rectus Abdominis','Obliques','Hip Flexors'], previewEmoji: ''),
        Exercise(id: 'leg_raise', name: 'Hanging Leg Raise', muscleGroup: 'Core',
          difficulty: 'Intermediate', equipment: 'Pull-up Bar', durationSeconds: 0,
          sets: 3, reps: '10-15', gifUrl: 'Hanging_Leg_Raise',
          description: 'Targets lower abdominals and hip flexors. The hang decompresses the spine as a bonus.',
          steps: ['Hang from bar overhand grip, body extended.','Keep legs together, engage core.','Raise legs straight until parallel to floor.','Lower slowly — no swinging.'],
          formCues: ['Avoid swinging — momentum removes ab work.','Slow lowering (3-4 s).','Posterior pelvic tilt at top maximises lower ab.','Use ab straps if grip fails.'],
          kalories: 6, muscles: ['Lower Rectus Abdominis','Hip Flexors','Obliques'], previewEmoji: ''),
        Exercise(id: 'mountain_climber', name: 'Mountain Climbers', muscleGroup: 'Core',
          difficulty: 'Beginner', equipment: 'None', durationSeconds: 40,
          sets: 3, reps: '20 each side', gifUrl: 'Mountain_Climbers',
          description: 'Combines core strengthening with cardio conditioning. Knee-drive trains core under instability.',
          steps: ['High plank — hands under shoulders, body straight.','Drive right knee toward chest.','Switch, extending right leg while driving left knee.','Alternate legs continuously.'],
          formCues: ['Hips level — not rising.','Core braced, back flat.','Faster = more cardio; slower = more core.','Shoulders over wrists.'],
          kalories: 8, muscles: ['Rectus Abdominis','Obliques','Hip Flexors','Shoulders'], previewEmoji: ''),
        Exercise(id: 'russian_twist', name: 'Russian Twist', muscleGroup: 'Core',
          difficulty: 'Beginner', equipment: 'None', durationSeconds: 45,
          sets: 3, reps: '20 each side', gifUrl: 'Russian_Twist',
          description: 'Develops rotational core strength critical for throwing, swinging, and changing direction.',
          steps: ['Sit, knees bent, feet elevated slightly.','Lean back 45° from floor.','Clasp hands or hold weight at chest.','Rotate torso right then left — one rep.'],
          formCues: ['Move from torso not just arms.','Lower back from rounding.','Elevated feet increases difficulty.','Slow controlled tempo.'],
          kalories: 5, muscles: ['Obliques','Rectus Abdominis','Hip Flexors'], previewEmoji: ''),
        Exercise(id: 'dead_bug', name: 'Dead Bug', muscleGroup: 'Core',
          difficulty: 'Beginner', equipment: 'None', durationSeconds: 45,
          sets: 3, reps: '10 each side', gifUrl: 'Dead_Bug',
          description: 'The safest and most effective exercise for anti-extension core stability.',
          steps: ['Lie on back, arms toward ceiling, knees at 90° above hips.','Press lower back firmly to floor throughout.','Slowly lower right arm overhead and extend left leg.','Stop before limbs touch floor. Return. Opposite side.'],
          formCues: ['Lower back stays pressed to floor always.','Move slowly with full control.','Exhale completely as you extend limbs.','Reduce range if lower back lifts.'],
          kalories: 3, muscles: ['Transverse Abdominis','Rectus Abdominis','Multifidus'], previewEmoji: ''),
      ],
    ),

    MuscleGroup(
      id: 'calves', name: 'Calves', icon: 'calves', color: 0xFF26C6DA,
      exercises: [
        Exercise(id: 'standing_calf_raise', name: 'Standing Calf Raise', muscleGroup: 'Calves',
          difficulty: 'Beginner', equipment: 'None / Step', durationSeconds: 0,
          sets: 4, reps: '15-20', gifUrl: 'Standing_Calf_Raises',
          description: 'Primary exercise for the gastrocnemius. Full range and pause at top and bottom eliminate momentum.',
          steps: ['Stand on raised surface with heels hanging off edge.','Lower heels as far as comfortable — full stretch.','Rise onto balls of feet as high as possible.','Pause 1 second at peak squeezing calves.','Lower under control.'],
          formCues: ['Full range — no partial reps.','Pause at top and bottom.','Knees straight to target gastrocnemius.','2 up, 1 hold, 3 down.'],
          kalories: 5, muscles: ['Gastrocnemius','Soleus'], previewEmoji: ''),
        Exercise(id: 'single_leg_calf_raise', name: 'Single-Leg Calf Raise', muscleGroup: 'Calves',
          difficulty: 'Intermediate', equipment: 'None / Step', durationSeconds: 0,
          sets: 3, reps: '15 each leg', gifUrl: 'Standing_Calf_Raises',
          description: 'Doubles the load on one calf using only bodyweight. Trains proprioception and ankle stability.',
          steps: ['Stand on one foot on step, hold wall lightly for balance.','Lower heel as far as possible off edge.','Rise as high as possible on ball of foot.','Hold 1 second at top, lower slowly.','Complete all reps before switching.'],
          formCues: ['Full stretch at bottom is key.','Hold a dumbbell for progression.','Hold wall lightly if balance difficult.','Calf does all the work.'],
          kalories: 5, muscles: ['Gastrocnemius','Soleus','Tibialis Anterior'], previewEmoji: ''),
        Exercise(id: 'jump_rope_calf', name: 'Jump Rope / Skipping', muscleGroup: 'Calves',
          difficulty: 'Beginner', equipment: 'Jump Rope', durationSeconds: 120,
          sets: 3, reps: '2 min', gifUrl: 'Rope_Jumping',
          description: 'Most calorie-efficient cardio that naturally loads the calves with each jump.',
          steps: ['Handle each hand, rope behind heels.','Swing rope forward overhead, jump over with both feet.','Stay on balls of feet, slight knee bend.','Keep elbows close, rotate from wrists.','Consistent rhythmic jump height.'],
          formCues: ['Jump only 2-4 cm — higher wastes energy.','Elbows tucked.','Balls of feet throughout.','Look straight ahead.'],
          kalories: 13, muscles: ['Gastrocnemius','Soleus','Cardiovascular System'], previewEmoji: ''),
      ],
    ),

    MuscleGroup(
      id: 'glutes', name: 'Glutes', icon: 'glutes', color: 0xFFEC407A,
      exercises: [
        Exercise(id: 'hip_thrust', name: 'Barbell Hip Thrust', muscleGroup: 'Glutes',
          difficulty: 'Intermediate', equipment: 'Barbell', durationSeconds: 0,
          sets: 4, reps: '10-12', gifUrl: 'Barbell_Hip_Thrust',
          description: 'Most effective exercise for glute hypertrophy, consistently outperforming squats in EMG activation studies.',
          steps: ['Sit on floor, upper back against bench, barbell across hips.','Feet flat, hip-width, barbell pad for comfort.','Drive through heels, thrust hips toward ceiling.','Squeeze glutes hard at top. Lower under control.'],
          formCues: ['Squeeze glutes — actively contract.','Chin-tuck throughout.','Feet flat, heels not rising.','Top: straight line from knees to shoulders.'],
          kalories: 9, muscles: ['Gluteus Maximus','Hamstrings','Adductors'], previewEmoji: ''),
        Exercise(id: 'glute_kickback', name: 'Glute Kickback', muscleGroup: 'Glutes',
          difficulty: 'Beginner', equipment: 'None', durationSeconds: 0,
          sets: 3, reps: '15 each side', gifUrl: 'Glute_Kickback',
          description: 'Isolates gluteus maximus through pure hip extension, developing the mind-muscle connection.',
          steps: ['Start on all fours — hands under shoulders, knees under hips.','Core braced, back flat.','Drive one heel toward ceiling, fully extending hip.','Squeeze glute at top 1-2 seconds.','Lower under control. Switch sides.'],
          formCues: ['Do not rotate hips.','Hip extension not back extension.','Crush heel toward glute at top.','Ankle band for resistance.'],
          kalories: 4, muscles: ['Gluteus Maximus','Hamstrings'], previewEmoji: ''),
        Exercise(id: 'sumo_squat', name: 'Sumo Squat', muscleGroup: 'Glutes',
          difficulty: 'Beginner', equipment: 'Dumbbells', durationSeconds: 0,
          sets: 4, reps: '12-15', gifUrl: 'Sumo_Deadlift',
          description: 'Wide stance places greater emphasis on glutes and adductors compared to conventional squat.',
          steps: ['Feet significantly wider than shoulder-width, toes at 45°.','Hold dumbbell or kettlebell between legs.','Brace core, push hips back as you lower.','Descend until thighs parallel, knees track toes.','Drive through heels, squeeze glutes and inner thighs.'],
          formCues: ['Knees track over toes — no caving.','Chest up, spine neutral.','Feel inner thighs and glutes working.','Wider stance = more glutes and adductors.'],
          kalories: 9, muscles: ['Gluteus Maximus','Adductors','Quadriceps','Hamstrings'], previewEmoji: ''),
        Exercise(id: 'glute_bridge', name: 'Glute Bridge', muscleGroup: 'Glutes',
          difficulty: 'Beginner', equipment: 'None', durationSeconds: 0,
          sets: 4, reps: '15-20', gifUrl: 'Single_Leg_Glute_Bridge',
          description: 'Bodyweight version of the hip thrust. Essential glute activation with no equipment.',
          steps: ['Lie on back, knees bent, feet flat hip-width.','Press arms flat on floor for stability.','Drive through heels thrusting hips toward ceiling.','Squeeze glutes hard at top. Hold 1-2 seconds.','Lower slowly without touching floor between reps.'],
          formCues: ['Squeeze glutes not lower back.','Ribs down — do not flare them.','Full hip extension at top.','Single-leg version for progression.'],
          kalories: 5, muscles: ['Gluteus Maximus','Hamstrings','Core'], previewEmoji: ''),
      ],
    ),

    MuscleGroup(
      id: 'forearms', name: 'Forearms', icon: 'forearms', color: 0xFF8D6E63,
      exercises: [
        Exercise(id: 'wrist_curl', name: 'Wrist Curl', muscleGroup: 'Forearms',
          difficulty: 'Beginner', equipment: 'Dumbbells', durationSeconds: 0,
          sets: 3, reps: '15-20', gifUrl: 'Seated_Dumbbell_Palms-Up_Wrist_Curl',
          description: 'Targets wrist flexors — the muscles responsible for grip strength and forearm thickness.',
          steps: ['Sit, forearms on thighs, palms up.','Hold dumbbells with wrists beyond knees.','Allow weight to roll to fingertips.','Curl wrists upward as far as possible.','Lower slowly.'],
          formCues: ['Weight rolls to fingertips for full range.','Forearms flat on thighs.','Appropriate weight for full range.','Pause at top.'],
          kalories: 3, muscles: ['Wrist Flexors','Forearm Muscles'], previewEmoji: ''),
        Exercise(id: 'reverse_wrist_curl', name: 'Reverse Wrist Curl', muscleGroup: 'Forearms',
          difficulty: 'Beginner', equipment: 'Dumbbells', durationSeconds: 0,
          sets: 3, reps: '15-20', gifUrl: 'Seated_Dumbbell_Palms-Down_Wrist_Curl',
          description: 'Works wrist extensors — neglected muscles. Prevents tennis elbow and improves stability.',
          steps: ['Sit, forearms on thighs, palms down.','Hold dumbbells overhand grip.','Lower wrists toward floor.','Curl wrists upward, lifting backs of hands.','Lower under control.'],
          formCues: ['Lighter weight than wrist curls.','Forearms flat on thighs.','Pair with wrist curls for balance.','Slow tempo reduces elbow strain.'],
          kalories: 3, muscles: ['Wrist Extensors','Brachioradialis'], previewEmoji: ''),
        Exercise(id: 'farmers_walk', name: "Farmer's Walk", muscleGroup: 'Forearms',
          difficulty: 'Intermediate', equipment: 'Dumbbells', durationSeconds: 30,
          sets: 3, reps: '30-40 meters', gifUrl: 'Farmers_Walk',
          description: 'Trains grip, forearm endurance, core stability, and cardio simultaneously — the most functional exercise.',
          steps: ['Pick up heavy dumbbells in each hand. Stand tall.','Brace core, pull shoulder blades back and down.','Walk forward with controlled steps.','Keep grip strong, posture upright.','Set down with control.'],
          formCues: ['Weights do not pull shoulders forward.','Shorter controlled steps.','Core braced to protect spine.','Set down safely when grip fails.'],
          kalories: 8, muscles: ['Wrist Flexors','Forearms','Traps','Core','Legs'], previewEmoji: ''),
      ],
    ),

    MuscleGroup(
      id: 'cardio', name: 'Cardio', icon: 'cardio', color: 0xFFFF7043,
      exercises: [
        Exercise(id: 'jumping_jacks', name: 'Jumping Jacks', muscleGroup: 'Cardio',
          difficulty: 'Beginner', equipment: 'None', durationSeconds: 60,
          sets: 3, reps: '30-60 sec', gifUrl: 'Rope_Jumping',
          description: 'Foundational cardio exercise that elevates heart rate rapidly while engaging the entire body.',
          steps: ['Stand upright, feet together, arms at sides.','Jump spreading feet wide while raising arms overhead.','Jump again bringing feet together and arms down.','Maintain steady rhythmic pace.'],
          formCues: ['Land softly on balls of feet.','Core lightly engaged.','Steady rhythm.','Full arm swings.'],
          kalories: 10, muscles: ['Full Body','Cardiovascular System'], previewEmoji: ''),
        Exercise(id: 'burpees', name: 'Burpees', muscleGroup: 'Cardio',
          difficulty: 'Intermediate', equipment: 'None', durationSeconds: 0,
          sets: 3, reps: '10-15', gifUrl: 'Mountain_Climbers',
          description: 'Push-up plus jump plus squat in one explosive movement — exceptional calorie burn and conditioning.',
          steps: ['Jump feet back to high plank.','Perform push-up — chest to floor.','Press up and jump feet forward to hands.','Explode upward into jump, arms overhead.','Land softly, repeat immediately.'],
          formCues: ['Land softly from jump.','Strong plank in push-up.','Push-up can be eliminated for regression.','Quality over speed.'],
          kalories: 14, muscles: ['Full Body','Pectorals','Triceps','Quads','Glutes','Core'], previewEmoji: ''),
        Exercise(id: 'high_knees', name: 'High Knees', muscleGroup: 'Cardio',
          difficulty: 'Beginner', equipment: 'None', durationSeconds: 45,
          sets: 3, reps: '30-45 sec', gifUrl: 'Jogging_Treadmill',
          description: 'Combines running mechanics with core engagement. Elevates heart rate while training hip flexors.',
          steps: ['Stand upright, feet hip-width, arms bent at 90°.','Run in place, driving right knee toward chest.','Switch, extending right while driving left knee.','Pump arms in opposition.'],
          formCues: ['Knees to at least hip height.','Balls of feet throughout.','Core tight — no torso rocking.','Arms drive pace.'],
          kalories: 12, muscles: ['Hip Flexors','Quadriceps','Calves','Core'], previewEmoji: ''),
        Exercise(id: 'box_jump', name: 'Box Jump', muscleGroup: 'Cardio',
          difficulty: 'Intermediate', equipment: 'Plyo Box', durationSeconds: 0,
          sets: 4, reps: '6-8', gifUrl: 'Front_Box_Jump',
          description: 'Trains explosive lower body power, developing fast-twitch fibres in quads, glutes, and calves.',
          steps: ['Stand facing box 30-60 cm high.','Dip into quarter squat, swing arms back.','Explode upward, swing arms forward driving knees up.','Land softly on box, both feet flat, knees bent.','Stand tall then step down carefully.'],
          formCues: ['Land softly.','Knees track toes on landing.','Step down — do not jump down.','Lower box until form is perfect.'],
          kalories: 12, muscles: ['Quadriceps','Glutes','Calves','Hamstrings'], previewEmoji: ''),
        Exercise(id: 'bear_crawl', name: 'Bear Crawl', muscleGroup: 'Cardio',
          difficulty: 'Intermediate', equipment: 'None', durationSeconds: 30,
          sets: 3, reps: '20 meters', gifUrl: 'Mountain_Climbers',
          description: 'Builds full-body coordination, core strength, and conditioning on all fours with knees hovering.',
          steps: ['Start on all fours, hands under shoulders, knees under hips.','Lift knees 2-5 cm off floor — they stay there throughout.','Move forward stepping right hand and left foot simultaneously.','Then left hand and right foot. Continue forward.','Keep back flat and hips low.'],
          formCues: ['Hips must not rise — parallel to floor.','Back flat like a table top.','Controlled deliberate pattern.','Reverse direction for more challenge.'],
          kalories: 10, muscles: ['Core','Shoulders','Quadriceps','Hip Flexors'], previewEmoji: ''),
      ],
    ),

    MuscleGroup(
      id: 'trapezius', name: 'Trapezius', icon: 'trapezius', color: 0xFF8E24AA,
      description: 'The trapezius spans the upper back and neck, controlling scapular elevation, retraction, and depression.',
      exercises: [
        Exercise(id: 'barbell_shrug', name: 'Barbell Shrug', muscleGroup: 'Trapezius',
          difficulty: 'Beginner', equipment: 'Barbell', durationSeconds: 45,
          sets: 4, reps: '12-15', gifUrl: 'Barbell_Shrug',
          description: 'Gold-standard trap builder allowing heavy loading through scapular elevation range.',
          steps: ['Stand feet hip-width, barbell overhand grip.','Arms straight, neck neutral.','Shrug shoulders straight up toward ears as high as possible.','Hold peak 1 second.','Lower slowly — 2 seconds descent.'],
          formCues: ['Shrug straight UP — no shoulder rolling.','Neck long — do not crane forward.','Full range — ears to shoulders.','Hold squeeze at top.'],
          kalories: 7, muscles: ['Upper Trapezius','Levator Scapulae'], previewEmoji: ''),
        Exercise(id: 'dumbbell_shrug', name: 'Dumbbell Shrug', muscleGroup: 'Trapezius',
          difficulty: 'Beginner', equipment: 'Dumbbells', durationSeconds: 45,
          sets: 3, reps: '15-20', gifUrl: 'Dumbbell_Shrug',
          description: 'Natural hand position and greater range than barbell shrug, reducing wrist strain.',
          steps: ['Hold dumbbells at sides, palms in.','Stand tall, shoulders relaxed, chest up.','Shrug both shoulders toward ears.','Hold 1 second at top.','Lower under control.'],
          formCues: ['Neutral grip reduces wrist strain.','Core braced — no leaning.','No momentum.','Feel upper trap burning at peak.'],
          kalories: 6, muscles: ['Upper Trapezius','Levator Scapulae'], previewEmoji: ''),
        Exercise(id: 'overhead_shrug', name: 'Overhead Trap Shrug', muscleGroup: 'Trapezius',
          difficulty: 'Intermediate', equipment: 'Dumbbells', durationSeconds: 40,
          sets: 3, reps: '12-15', gifUrl: 'Dumbbell_Shrug',
          description: 'Arms overhead isolates lower and middle trapezius — critical for shoulder health.',
          steps: ['Press dumbbells overhead until arms fully locked out.','Maintain locked-out position throughout.','Allow shoulder blades to elevate (shrug up) fully.','Actively depress scapulae — pull shoulders from ears.','Pause at bottom 1 second.'],
          formCues: ['Arms locked — scapular movement only.','The "down" phase is the working phase.','Think "shoulder blades in back pockets."','Vertical torso.'],
          kalories: 5, muscles: ['Lower Trapezius','Middle Trapezius','Serratus Anterior'], previewEmoji: ''),
        Exercise(id: 'y_t_w_raise', name: 'Y-T-W Raise', muscleGroup: 'Trapezius',
          difficulty: 'Beginner', equipment: 'Dumbbells', durationSeconds: 45,
          sets: 3, reps: '12 each', gifUrl: 'Lying_Rear_Delt_Raise',
          description: 'Targets all three trapezius portions plus rhomboids and rear delts — essential for scapular health.',
          steps: ['Lie face-down on incline bench or hinge forward at hips.','Hold light dumbbells, thumbs up.','Y raise: arms in Y shape overhead (lower trap).','T raise: arms out to sides (middle trap).','W raise: elbows 90°, raise to shoulder height.'],
          formCues: ['Very light weight — small movement.','Squeeze shoulder blades on each rep.','Do not shrug — shoulders depressed.','Slow and deliberate.'],
          kalories: 4, muscles: ['Upper Trapezius','Middle Trapezius','Lower Trapezius','Rear Deltoids'], previewEmoji: ''),
      ],
    ),

    MuscleGroup(
      id: 'neck', name: 'Neck', icon: 'neck', color: 0xFF546E7A,
      description: 'Neck muscles stabilise the head, enable rotation and flexion, and reduce injury risk in contact sports.',
      exercises: [
        Exercise(id: 'neck_extension', name: 'Neck Extension', muscleGroup: 'Neck',
          difficulty: 'Beginner', equipment: 'Bodyweight', durationSeconds: 40,
          sets: 3, reps: '15-20', gifUrl: 'Superman',
          description: 'Targets posterior neck muscles responsible for keeping the head upright.',
          steps: ['Lie face-down on bench, head hanging off edge.','Place hands behind head or hold small weight.','Lower chin toward floor under control.','Raise head back to neutral by contracting posterior neck.','Do not hyperextend — stop at neutral.'],
          formCues: ['Move slowly — small muscle, long lever.','Never jerk your neck.','Stop for any sharp pain or dizziness.','Start bodyweight before adding plate.'],
          kalories: 3, muscles: ['Splenius Capitis','Cervical Erectors','Upper Trapezius'], previewEmoji: ''),
        Exercise(id: 'neck_flexion', name: 'Neck Flexion', muscleGroup: 'Neck',
          difficulty: 'Beginner', equipment: 'Bodyweight', durationSeconds: 40,
          sets: 3, reps: '15-20', gifUrl: 'Lying_Face_Up_Plate_Neck_Resistance',
          description: 'Trains sternocleidomastoid and deep cervical flexors. Strong anterior neck reduces concussion risk.',
          steps: ['Lie face-up on bench, head hanging off edge.','Allow head to drop back — full extension.','Curl chin toward chest using neck muscles.','Lower slowly back to start.'],
          formCues: ['Full range — chin to chest at top.','Stop if dizziness occurs.','Start with no added weight.','Progress very gradually.'],
          kalories: 3, muscles: ['Sternocleidomastoid','Anterior Scalene','Deep Cervical Flexors'], previewEmoji: ''),
        Exercise(id: 'neck_lateral_flexion', name: 'Neck Lateral Flexion', muscleGroup: 'Neck',
          difficulty: 'Beginner', equipment: 'Resistance Band', durationSeconds: 40,
          sets: 3, reps: '12-15 per side', gifUrl: 'Isometric_Neck_Exercise_-_Sides',
          description: 'Targets scalenes and lateral sternocleidomastoid. Important for balanced neck development.',
          steps: ['Sit or stand with good posture.','Place right hand on right side of head above ear.','Gently resist with hand while tilting head right.','Tilt head toward shoulder against resistance.','Return slowly. Complete reps then switch sides.'],
          formCues: ['Ear toward shoulder — do not rotate head.','Opposite shoulder stays down.','Minimal resistance — fatigue quickly.','Equal work both sides.'],
          kalories: 2, muscles: ['Scalenes','Sternocleidomastoid','Lateral Cervical Flexors'], previewEmoji: ''),
        Exercise(id: 'wrestlers_bridge', name: "Wrestler's Bridge", muscleGroup: 'Neck',
          difficulty: 'Advanced', equipment: 'None', durationSeconds: 30,
          sets: 3, reps: '30-60 sec hold', gifUrl: 'Single_Leg_Glute_Bridge',
          description: 'Full-neck isometric training extension, lateral stability, and rotational strength simultaneously.',
          steps: ['Lie on back on mat.','Place top of head on mat with chin tucked.','Bridge hips up so only head and feet contact mat.','Place hands on chest or extend arms for support first.','Hold the bridge position.'],
          formCues: ['Start with hands as support.','Controlled rocking only.','Stop if you feel neck pain.','Build duration over weeks before rocking.'],
          kalories: 4, muscles: ['All Cervical Extensors','Sternocleidomastoid','Upper Trapezius'], previewEmoji: ''),
      ],
    ),

    MuscleGroup(
      id: 'lower_back', name: 'Lower Back', icon: 'lower_back', color: 0xFF6D4C41,
      description: 'The erector spinae and multifidus stabilise the spine. A strong lower back is the foundation for every major lift.',
      exercises: [
        Exercise(id: 'hyperextension', name: 'Back Extension', muscleGroup: 'Lower Back',
          difficulty: 'Beginner', equipment: 'Hyperextension Bench', durationSeconds: 45,
          sets: 3, reps: '12-20', gifUrl: 'Hyperextensions_Back_Extensions',
          description: 'Directly isolates the erector spinae through full lumbar flexion-to-extension range.',
          steps: ['Position on hyperextension bench, hips on pad, ankles locked.','Arms crossed on chest or hands behind head.','Hinge at hips, lower torso toward floor.','Contract glutes and lower back to raise torso to horizontal.','Do not hyperextend past neutral.'],
          formCues: ['Stop at neutral — hyperextension compresses discs.','Squeeze glutes at top.','Add plate on chest for progression.','Control the descent.'],
          kalories: 6, muscles: ['Erector Spinae','Glutes','Hamstrings'], previewEmoji: ''),
        Exercise(id: 'good_morning', name: 'Good Morning', muscleGroup: 'Lower Back',
          difficulty: 'Intermediate', equipment: 'Barbell', durationSeconds: 50,
          sets: 3, reps: '8-12', gifUrl: 'Good_Morning',
          description: 'Barbell hip-hinge loading the entire posterior chain — a powerlifting staple for deadlift development.',
          steps: ['Barbell on upper traps. Stand feet hip-width, slight knee bend.','Hinge at hips pushing backward, lowering torso.','Maintain flat back and strong brace.','Lower until torso near parallel — hamstring stretch.','Drive hips forward to stand.'],
          formCues: ['HIP HINGE — push hips back not down.','Neutral spine throughout.','Light weight until pattern mastered.','Show your chest to the floor.'],
          kalories: 9, muscles: ['Erector Spinae','Hamstrings','Glutes','Multifidus'], previewEmoji: ''),
        Exercise(id: 'superman_hold', name: 'Superman Hold', muscleGroup: 'Lower Back',
          difficulty: 'Beginner', equipment: 'None', durationSeconds: 40,
          sets: 3, reps: '10-15 (3 s hold)', gifUrl: 'Superman',
          description: 'Floor-based lower back isolation with no equipment — perfect for beginners.',
          steps: ['Lie face-down, arms extended front, legs straight.','Simultaneously lift arms, chest, and legs off floor.','Hold 3 seconds, squeeze glutes and lower back.','Lower everything back to floor.'],
          formCues: ['Squeeze glutes — protects lumbar spine.','Look at floor.','Lift as high as comfortably possible.','Breathe steadily.'],
          kalories: 4, muscles: ['Erector Spinae','Multifidus','Glutes'], previewEmoji: ''),
        Exercise(id: 'bird_dog', name: 'Bird Dog', muscleGroup: 'Lower Back',
          difficulty: 'Beginner', equipment: 'None', durationSeconds: 45,
          sets: 3, reps: '10 per side', gifUrl: 'Dead_Bug',
          description: 'Trains anti-rotation spinal stability, activating multifidus and transverse abdominis deeply.',
          steps: ['Start on all fours — hands under shoulders, knees under hips.','Brace core, neutral spine.','Simultaneously extend right arm forward and left leg back.','Hold 2 seconds — form a straight line.','Return without hip drop. Opposite side.'],
          formCues: ['Hips must not rotate.','Extend slowly.','Squeeze glute on extended leg.','Lower back flat.'],
          kalories: 3, muscles: ['Multifidus','Erector Spinae','Glutes','Transverse Abdominis'], previewEmoji: ''),
        Exercise(id: 'reverse_hyperextension', name: 'Reverse Hyperextension', muscleGroup: 'Lower Back',
          difficulty: 'Intermediate', equipment: 'Bench', durationSeconds: 45,
          sets: 3, reps: '12-15', gifUrl: 'Reverse_Hyperextension',
          description: 'Torso stationary, legs extend — unique lumbar traction effect while building erectors and glutes.',
          steps: ['Lie face-down on high bench, hips at edge.','Grip bench firmly.','Allow legs to hang down — full lumbar flexion.','Swing legs up to horizontal by contracting glutes and lower back.','Hold 1 second then lower slowly.'],
          formCues: ['Control the swing — no kipping.','Stop at horizontal.','The descent provides traction — control it.','Add ankle weights for progression.'],
          kalories: 6, muscles: ['Erector Spinae','Glutes','Hamstrings'], previewEmoji: ''),
      ],
    ),

    MuscleGroup(
      id: 'hamstrings', name: 'Hamstrings', icon: 'legs', color: 0xFF00838F,
      description: 'The hamstrings flex the knee and extend the hip. Directly strengthening them is critical for injury prevention.',
      exercises: [
        Exercise(id: 'nordic_curl', name: 'Nordic Hamstring Curl', muscleGroup: 'Hamstrings',
          difficulty: 'Advanced', equipment: 'Partner', durationSeconds: 60,
          sets: 3, reps: '5-8', gifUrl: 'Ball_Leg_Curl',
          description: 'Reduces hamstring strain injury risk by up to 51%. Trains hamstrings at long muscle lengths.',
          steps: ['Kneel on mat with ankles secured by partner or heavy object.','Torso upright, arms at sides.','Slowly lower forward by allowing knees to extend.','Lower as far as controlled form allows.','Use hands to catch if needed. Curl back up.'],
          formCues: ['Eccentric lowering is the key — resist it hard.','Keep hips extended throughout.','Use thin mat for knee comfort.','Start with 3-5 reps only.'],
          kalories: 8, muscles: ['Biceps Femoris','Semitendinosus','Semimembranosus'], previewEmoji: ''),
        Exercise(id: 'romanian_deadlift_ham', name: 'Romanian Deadlift (Hamstring Focus)', muscleGroup: 'Hamstrings',
          difficulty: 'Intermediate', equipment: 'Dumbbells', durationSeconds: 45,
          sets: 4, reps: '10-12', gifUrl: 'Romanian_Deadlift',
          description: 'Dumbbell RDL allows greater range of motion and easier form control for hamstring isolation.',
          steps: ['Stand holding dumbbells at sides, feet hip-width.','Slight bend in knees maintained throughout.','Hinge at hips pushing backward, dumbbells down thighs.','Lower until strong hamstring stretch.','Drive hips forward to stand.'],
          formCues: ['Push hips BACK — hip hinge not squat.','Flat back throughout.','Hamstring stretch guides depth.','Drive hips through at top, squeeze glutes.'],
          kalories: 10, muscles: ['Hamstrings','Glutes','Erector Spinae'], previewEmoji: ''),
        Exercise(id: 'glute_ham_bridge', name: 'Single-Leg Glute Bridge', muscleGroup: 'Hamstrings',
          difficulty: 'Intermediate', equipment: 'None', durationSeconds: 45,
          sets: 3, reps: '12-15 per side', gifUrl: 'Single_Leg_Glute_Bridge',
          description: 'Strongly activates hamstrings as hip extensor while challenging hip stability on one leg.',
          steps: ['Lie on back, knees bent, one foot flat on floor.','Extend other leg straight toward ceiling.','Drive through grounded heel thrusting hips up.','Squeeze glute and hamstring at top.','Lower slowly. Switch.'],
          formCues: ['Non-working hip stays level.','Drive through heel not toes.','Full hip extension at top.','3 seconds lowering.'],
          kalories: 6, muscles: ['Hamstrings','Gluteus Maximus','Core'], previewEmoji: ''),
        Exercise(id: 'swiss_ball_leg_curl', name: 'Swiss Ball Leg Curl', muscleGroup: 'Hamstrings',
          difficulty: 'Intermediate', equipment: 'Swiss Ball', durationSeconds: 45,
          sets: 3, reps: '10-15', gifUrl: 'Ball_Leg_Curl',
          description: 'Challenges hamstrings as both knee flexors and hip extensors simultaneously with a stability ball.',
          steps: ['Lie on back, heels on Swiss ball.','Drive hips up into bridge — straight line shoulders to heels.','Maintain hip bridge throughout.','Curl ball toward glutes by flexing knees.','Extend legs back without dropping hips.'],
          formCues: ['Do not let hips drop.','Curl slowly — instability is hard.','Single-leg is advanced progression.','Point toes up to isolate hamstrings.'],
          kalories: 6, muscles: ['Biceps Femoris','Glutes','Core'], previewEmoji: ''),
        Exercise(id: 'good_morning_ham', name: 'Good Morning (Bodyweight)', muscleGroup: 'Hamstrings',
          difficulty: 'Beginner', equipment: 'Bodyweight', durationSeconds: 40,
          sets: 3, reps: '15-20', gifUrl: 'Good_Morning',
          description: 'Safest introduction to the hip-hinge pattern, priming hamstrings and lower back.',
          steps: ['Stand feet hip-width, hands clasped behind head.','Slight bend in knees maintained throughout.','Hinge at hips pushing backward until torso near horizontal.','Feel the stretch in your hamstrings.','Drive hips forward to return.'],
          formCues: ['Push hips BACK — not knees.','Lower back flat — no rounding.','Hamstrings should feel tight at bottom.','Neutral head position.'],
          kalories: 5, muscles: ['Hamstrings','Glutes','Erector Spinae'], previewEmoji: ''),
      ],
    ),

    MuscleGroup(
      id: 'quadriceps', name: 'Quadriceps', icon: 'quadriceps', color: 0xFF1E88E5,
      description: 'The four heads of the quadriceps are the primary knee extensors and the largest muscle group by mass.',
      exercises: [
        Exercise(id: 'bulgarian_split_squat', name: 'Bulgarian Split Squat', muscleGroup: 'Quadriceps',
          difficulty: 'Intermediate', equipment: 'Dumbbells', durationSeconds: 55,
          sets: 3, reps: '10-12 per leg', gifUrl: 'Split_Squats',
          description: 'Highest quad EMG activation of any squat variation. Rear foot elevation maximises range of motion.',
          steps: ['Stand 60 cm in front of bench, facing away.','Rear foot top on bench.','Hold dumbbells at sides.','Lower bending front knee, torso upright.','Lower until rear knee nearly touches floor.','Drive through front heel to return.'],
          formCues: ['Front foot far enough forward.','Torso upright — quad not hip flexor.','Drive front heel on ascent.','Rear leg for balance only.'],
          kalories: 10, muscles: ['Rectus Femoris','Vastus Lateralis','Vastus Medialis','Glutes'], previewEmoji: ''),
        Exercise(id: 'front_squat', name: 'Front Squat', muscleGroup: 'Quadriceps',
          difficulty: 'Advanced', equipment: 'Barbell', durationSeconds: 60,
          sets: 4, reps: '6-8', gifUrl: 'Front_Squat_Clean_Grip',
          description: 'Bar in front demands upright torso and shifts more load to quads than a back squat.',
          steps: ['Bar at shoulder height in rack.','Step under bar, position across front deltoids.','Unrack with elbows driving high.','Squat with upright torso until below parallel.','Drive up through heels, elbows high.'],
          formCues: ['Elbows UP — bar rolls if they drop.','Upright torso is non-negotiable.','Brace hard.','Full depth.'],
          kalories: 12, muscles: ['Rectus Femoris','Vastus Lateralis','Vastus Medialis','Core'], previewEmoji: ''),
        Exercise(id: 'wall_sit', name: 'Wall Sit', muscleGroup: 'Quadriceps',
          difficulty: 'Beginner', equipment: 'Wall', durationSeconds: 60,
          sets: 3, reps: '45-90 sec hold', gifUrl: '',
          description: 'Isometric quad exercise building endurance and muscle fibre recruitment without joint impact.',
          steps: ['Back flat against wall.','Walk feet out and slide down until knees at 90°.','Thighs parallel to floor.','Back flat against wall throughout.','Hold for prescribed time.'],
          formCues: ['90-degree knee angle maximises stimulus.','Knees out — do not cave.','Back flat against wall.','Breathe steadily.'],
          kalories: 5, muscles: ['Rectus Femoris','Vastus Lateralis','Vastus Medialis','Glutes'], previewEmoji: ''),
        Exercise(id: 'step_up', name: 'Step-Up', muscleGroup: 'Quadriceps',
          difficulty: 'Beginner', equipment: 'None / Dumbbells', durationSeconds: 0,
          sets: 3, reps: '12 per leg', gifUrl: 'Dumbbell_Step_Ups',
          description: 'Unilateral quad exercise training balance and stability through full range of knee flexion.',
          steps: ['Stand in front of box or bench 30-50 cm high.','Place right foot fully on box.','Drive through right heel to step up, fully extending knee and hip.','Bring left foot up to meet right.','Step back down. Alternate or complete all one side.'],
          formCues: ['Drive through heel of working foot.','Torso upright.','Working leg does all the work.','Control the descent.'],
          kalories: 8, muscles: ['Quadriceps','Glutes','Hamstrings'], previewEmoji: ''),
        Exercise(id: 'sissy_squat', name: 'Sissy Squat', muscleGroup: 'Quadriceps',
          difficulty: 'Advanced', equipment: 'None', durationSeconds: 0,
          sets: 3, reps: '8-12', gifUrl: 'Barbell_Full_Squat',
          description: 'Maximally isolates the quadriceps by allowing knees to travel far forward while keeping hips extended.',
          steps: ['Hold wall lightly for balance, feet together.','Rise up on toes.','Lean torso back, allow knees to travel far forward.','Lower as if going to kneel.','Raise back by driving knees back and straightening body.'],
          formCues: ['Hips fully extended throughout.','Knee-forward position is correct and intentional.','Control the descent.','Partial range to start, build to full.'],
          kalories: 8, muscles: ['Rectus Femoris','Vastus Lateralis','Vastus Medialis','Vastus Intermedius'], previewEmoji: ''),
      ],
    ),

    MuscleGroup(
      id: 'hip_flexors', name: 'Hip Flexors', icon: 'hip_flexors', color: 0xFFE53935,
      description: 'The hip flexors pull the knee toward the chest and stabilise the lumbar spine. Weakness causes lower back pain.',
      exercises: [
        Exercise(id: 'hanging_knee_raise', name: 'Hanging Knee Raise', muscleGroup: 'Hip Flexors',
          difficulty: 'Intermediate', equipment: 'Pull-Up Bar', durationSeconds: 40,
          sets: 3, reps: '12-15', gifUrl: 'Hanging_Leg_Raise',
          description: 'Loads hip flexors at full shoulder elevation — the most demanding position for the iliopsoas.',
          steps: ['Hang from bar, overhand grip, arms extended.','Body hangs freely without swinging.','Brace core and curl knees toward chest.','Hips rise slightly at top.','Lower slowly back to dead hang.'],
          formCues: ['Control the swing — no kipping.','Posterior pelvic tilt at top.','Straight-leg version is advanced.','Pause 1 second at top.'],
          kalories: 6, muscles: ['Iliopsoas','Rectus Femoris','Rectus Abdominis'], previewEmoji: ''),
        Exercise(id: 'standing_hip_flexion', name: 'Standing Hip Flexion', muscleGroup: 'Hip Flexors',
          difficulty: 'Beginner', equipment: 'Resistance Band', durationSeconds: 40,
          sets: 3, reps: '15 per side', gifUrl: 'Hanging_Leg_Raise',
          description: 'Strengthens iliopsoas in its functional upright position — ideal for runners and cyclists.',
          steps: ['Stand holding wall for balance.','Resistance band on ankle, anchored behind.','Lift working knee forward and up until thigh parallel.','Pause at top 2 seconds.','Lower slowly. Switch sides.'],
          formCues: ['Standing leg straight, torso upright.','Do not lean back.','Drive the knee up not swing the ankle.','Slow controlled lowering.'],
          kalories: 3, muscles: ['Iliopsoas','Rectus Femoris','TFL'], previewEmoji: ''),
        Exercise(id: 'psoas_march', name: 'Psoas March', muscleGroup: 'Hip Flexors',
          difficulty: 'Beginner', equipment: 'None', durationSeconds: 40,
          sets: 3, reps: '20 per side', gifUrl: 'Dead_Bug',
          description: 'Primary rehabilitation and activation exercise for hip flexor weakness or lower back pain.',
          steps: ['Lie on back, knees bent 90°, feet flat.','Brace core, press lower back to floor.','Lift both feet so hips and knees at 90-90.','Slowly lower one foot toward floor without touching.','Return and alternate — marching motion.'],
          formCues: ['Lower back stays flat always.','Breathe out as you lower the leg.','Add band for resistance.','Slow and deliberate.'],
          kalories: 3, muscles: ['Iliopsoas','Transverse Abdominis','Rectus Abdominis'], previewEmoji: ''),
        Exercise(id: 'dragon_flag', name: 'Dragon Flag', muscleGroup: 'Hip Flexors',
          difficulty: 'Advanced', equipment: 'Bench', durationSeconds: 45,
          sets: 3, reps: '5-8', gifUrl: 'Hanging_Pike',
          description: 'Popularised by Bruce Lee. Elite full-body tension exercise training hip flexors, core, and entire anterior chain.',
          steps: ['Lie on bench, grip bench behind head with both hands.','Brace entire body and drive hips toward ceiling.','Extend until only upper back and shoulders on bench.','Lower body slowly as a rigid plank.','Stop just before touching. Raise back to vertical.'],
          formCues: ['Body must remain straight — no piking.','Lowering phase is the exercise — never rush.','Tuck dragon flag as regression.','Grip the bench firmly.'],
          kalories: 9, muscles: ['Iliopsoas','Rectus Abdominis','Hip Flexors','Anterior Chain'], previewEmoji: ''),
      ],
    ),

    MuscleGroup(
      id: 'adductors', name: 'Adductors', icon: 'adductors', color: 0xFFD81B60,
      description: 'The adductors pull the legs together and stabilise the pelvis. Adductor strains are common groin injuries in athletes.',
      exercises: [
        Exercise(id: 'lateral_lunge', name: 'Lateral Lunge', muscleGroup: 'Adductors',
          difficulty: 'Beginner', equipment: 'Bodyweight', durationSeconds: 45,
          sets: 3, reps: '12 per side', gifUrl: 'Dumbbell_Lunges',
          description: 'Trains adductors in a functional frontal-plane movement, also dynamically stretching the straight leg.',
          steps: ['Stand feet together.','Take a large step directly to the right.','Bend right knee, push hips back and right.','Left leg stays straight, foot flat.','Lower until right thigh parallel or below.','Drive through right heel to return.'],
          formCues: ['Straight leg truly straight.','Chest up — no rounding.','Bent leg foot stays flat.','Soft knee on landing.'],
          kalories: 7, muscles: ['Adductor Magnus','Glutes','Quadriceps','Hamstrings'], previewEmoji: ''),
        Exercise(id: 'copenhagen_plank', name: 'Copenhagen Plank', muscleGroup: 'Adductors',
          difficulty: 'Advanced', equipment: 'Bench', durationSeconds: 30,
          sets: 3, reps: '20-30 sec per side', gifUrl: 'Push_Up_to_Side_Plank',
          description: 'Highest adductor activation of any known exercise. Reduces groin injury rates by over 40%.',
          steps: ['Side plank with top foot resting on bench.','Body forms straight line from head to bottom foot.','Stack hips — do not let them sag.','Hold for prescribed duration.'],
          formCues: ['Adductor of top leg does the work.','Torso rigid — no rotation.','5 reps × 5 s to start.','Significant soreness expected.'],
          kalories: 5, muscles: ['Adductor Magnus','Adductor Longus','Gracilis','Core'], previewEmoji: ''),
        Exercise(id: 'inner_thigh_squeeze', name: 'Inner Thigh Squeeze', muscleGroup: 'Adductors',
          difficulty: 'Beginner', equipment: 'Pilates Ball', durationSeconds: 40,
          sets: 3, reps: '20-30 squeezes', gifUrl: 'Butt_Lift_Bridge',
          description: 'Pure adductor isometric contraction — simple, accessible, effective for rehabilitation.',
          steps: ['Sit upright on chair or lie with knees bent.','Place soft pilates ball or rolled towel between inner thighs.','Squeeze as hard as possible for 3 seconds.','Release slowly. Repeat.'],
          formCues: ['Progressive squeeze — build to max force.','Breathe normally during hold.','Good for rehabilitation.','Effective while seated.'],
          kalories: 2, muscles: ['Adductor Longus','Adductor Brevis','Gracilis'], previewEmoji: ''),
        Exercise(id: 'curtsy_lunge', name: 'Curtsy Lunge', muscleGroup: 'Adductors',
          difficulty: 'Intermediate', equipment: 'Bodyweight', durationSeconds: 45,
          sets: 3, reps: '12 per side', gifUrl: 'Dumbbell_Lunges',
          description: 'Cross-behind step creates medial loading pattern activating adductors and glute medius more than standard lunge.',
          steps: ['Stand feet together.','Step right foot diagonally back and left, crossing behind left leg.','Lower hips — right knee points left.','Both knees bent ~90° at bottom.','Drive through front heel to return. Switch.'],
          formCues: ['Front knee tracks over toes.','Torso tall.','Crossing pattern loads adductors uniquely.','Control the descent.'],
          kalories: 8, muscles: ['Adductor Magnus','Glute Medius','Quadriceps','Glutes'], previewEmoji: ''),
      ],
    ),

    MuscleGroup(
      id: 'abductors', name: 'Abductors', icon: 'abductors', color: 0xFF00ACC1,
      description: 'Hip abductors move the leg away from midline and stabilise the pelvis during every step. Weakness causes knee valgus.',
      exercises: [
        Exercise(id: 'clamshell', name: 'Clamshell', muscleGroup: 'Abductors',
          difficulty: 'Beginner', equipment: 'Resistance Band', durationSeconds: 40,
          sets: 3, reps: '20 per side', gifUrl: 'Thigh_Abductor',
          description: 'Foundational glute medius activation exercise used in physical therapy worldwide.',
          steps: ['Lie on side, hips and knees bent to 45°.','Resistance band above knees (optional).','Keep feet stacked and hips stacked — do not roll back.','Raise top knee toward ceiling as high as possible.','Hold 1 second. Lower slowly.'],
          formCues: ['Hips stacked vertically.','Contraction in outer glute not hip flexor.','Band increases difficulty.','Slow tempo.'],
          kalories: 3, muscles: ['Gluteus Medius','Gluteus Minimus','Piriformis'], previewEmoji: ''),
        Exercise(id: 'side_lying_abduction', name: 'Side-Lying Hip Abduction', muscleGroup: 'Abductors',
          difficulty: 'Beginner', equipment: 'None', durationSeconds: 40,
          sets: 3, reps: '20 per side', gifUrl: 'Lying_One-Arm_Lateral_Raise',
          description: 'Directly loads the gluteus medius through frontal plane motion. Ankle weights provide progression.',
          steps: ['Lie on side, legs straight and stacked.','Head on bottom arm.','Top leg straight and in line with body.','Raise top leg toward ceiling as high as possible.','Hold 1 second. Lower slowly. Switch.'],
          formCues: ['Pelvis must not rotate back.','Toe slightly down — targets glute medius.','Ankle weight 2-3 kg for progression.','Full range of motion.'],
          kalories: 3, muscles: ['Gluteus Medius','Gluteus Minimus','TFL'], previewEmoji: ''),
        Exercise(id: 'lateral_band_walk', name: 'Lateral Band Walk', muscleGroup: 'Abductors',
          difficulty: 'Beginner', equipment: 'Resistance Band', durationSeconds: 40,
          sets: 3, reps: '20 steps per direction', gifUrl: 'Lateral_Bound',
          description: 'Dynamic glute medius exercise training abduction under bodyweight — the functional sport pattern.',
          steps: ['Resistance band around ankles or above knees.','Athletic position — slight hip hinge, knees slightly bent.','Step laterally to the right, keeping band taut.','Step left foot to meet right, maintaining tension.','Complete reps right then reverse direction.'],
          formCues: ['Stay in athletic hinge position.','Band tension maintained — feet never fully together.','Short deliberate steps.','Toes pointing forward throughout.'],
          kalories: 4, muscles: ['Gluteus Medius','Gluteus Minimus','TFL'], previewEmoji: ''),
        Exercise(id: 'monster_walk', name: 'Monster Walk', muscleGroup: 'Abductors',
          difficulty: 'Beginner', equipment: 'Resistance Band', durationSeconds: 40,
          sets: 3, reps: '20 steps forward, 20 back', gifUrl: 'Lateral_Bound',
          description: 'Combines forward/backward band walking with abduction — diagonal vectors mimicking sport movements.',
          steps: ['Band around both ankles.','Wide athletic stance to create band tension.','Walk forward diagonally — right foot forward-right then left forward-left.','Maintain band tension throughout.','Walk backward using same pattern.'],
          formCues: ['Stay low — hip hinge throughout.','Toes forward or slightly out.','Slow controlled steps.','Wrap band above knees if it slides.'],
          kalories: 5, muscles: ['Gluteus Medius','Gluteus Minimus','Glutes'], previewEmoji: ''),
      ],
    ),

    MuscleGroup(
      id: 'serratus', name: 'Serratus Anterior', icon: 'serratus', color: 0xFF43A047,
      description: 'The serratus anterior wraps around the rib cage, protracting the scapula. Weakness causes winged scapula.',
      exercises: [
        Exercise(id: 'serratus_punch', name: 'Serratus Punch', muscleGroup: 'Serratus Anterior',
          difficulty: 'Beginner', equipment: 'Dumbbells', durationSeconds: 40,
          sets: 3, reps: '15-20 per side', gifUrl: 'Incline_Dumbbell_Press',
          description: 'Most direct isolation exercise for serratus anterior, targeting scapular protraction.',
          steps: ['Lie on back holding dumbbell in one hand, arm extended toward ceiling.','Start with shoulder blade resting on bench.','Without bending elbow, reach arm further toward ceiling.','Punching motion protracts scapula.','Hold 1 second. Lower.'],
          formCues: ['Elbow locked — all scapular movement.','Ribs on working side lift off bench.','Reach for ceiling not press dumbbell up.','Very light weight to start.'],
          kalories: 3, muscles: ['Serratus Anterior'], previewEmoji: ''),
        Exercise(id: 'push_up_plus', name: 'Push-Up Plus', muscleGroup: 'Serratus Anterior',
          difficulty: 'Beginner', equipment: 'None', durationSeconds: 40,
          sets: 3, reps: '15-20', gifUrl: 'Pushups',
          description: 'Push-up with scapular protraction at the top produces the highest serratus EMG of any exercise.',
          steps: ['Standard push-up position.','Perform regular push-up to full arm extension.','Add extra "plus" — push upper back further toward ceiling.','Shoulder blades should spread wide apart.','Hold 1 second at full protraction then return.'],
          formCues: ['Plus is about 3 cm of extra push.','Feel shoulder blades separate on back.','Core tight — rigid plank throughout.','No hip sagging during plus phase.'],
          kalories: 5, muscles: ['Serratus Anterior','Pectorals','Triceps'], previewEmoji: ''),
        Exercise(id: 'dumbbell_pullover', name: 'Dumbbell Pullover', muscleGroup: 'Serratus Anterior',
          difficulty: 'Intermediate', equipment: 'Dumbbells', durationSeconds: 45,
          sets: 3, reps: '12-15', gifUrl: 'Bent-Arm_Dumbbell_Pullover',
          description: 'Trains serratus anterior and lat through a shared overhead arc — classic bodybuilding movement.',
          steps: ['Lie perpendicular across bench, upper back on bench, hips low.','Hold single dumbbell with both hands under inner plate.','Start above chest, arms slightly bent.','Lower dumbbell backward over head in arc.','Feel deep stretch through lats and serratus.','Pull back to starting position.'],
          formCues: ['Hips remain low.','Elbows slightly bent throughout.','Inhale on way down.','Stretch-under-tension exercise — control it.'],
          kalories: 7, muscles: ['Serratus Anterior','Latissimus Dorsi','Pectoralis Major'], previewEmoji: ''),
        Exercise(id: 'landmine_press', name: 'Landmine Press', muscleGroup: 'Serratus Anterior',
          difficulty: 'Intermediate', equipment: 'Barbell', durationSeconds: 50,
          sets: 3, reps: '10-12 per side', gifUrl: 'Barbell_Shoulder_Press',
          description: 'Pressing arc demands continuous serratus engagement to maintain scapular upward rotation.',
          steps: ['Anchor barbell at floor corner or landmine attachment.','Hold far end at shoulder height.','Press bar forward and up in arc.','At top, reach further — protracting scapula.','Lower under control.'],
          formCues: ['Protraction at top is what makes this serratus exercise.','Core braced throughout.','Single-arm version trains anti-rotation.','Maintain the arc.'],
          kalories: 7, muscles: ['Serratus Anterior','Deltoid','Pectorals','Triceps'], previewEmoji: ''),
      ],
    ),

    MuscleGroup(
      id: 'obliques', name: 'Obliques', icon: 'obliques', color: 0xFFF4511E,
      description: 'The obliques rotate and laterally flex the trunk, and resist unwanted rotation — essential for rotational athletic movements.',
      exercises: [
        Exercise(id: 'side_plank', name: 'Side Plank', muscleGroup: 'Obliques',
          difficulty: 'Beginner', equipment: 'None', durationSeconds: 30,
          sets: 3, reps: '30-60 sec per side', gifUrl: 'Push_Up_to_Side_Plank',
          description: 'Gold-standard lateral core stability exercise training obliques, quadratus lumborum, and hip abductors.',
          steps: ['Lie on side, legs straight, feet stacked.','Bottom elbow under shoulder.','Lift hips off floor creating straight line head to feet.','Top hand on hip or extended toward ceiling.','Hold. Switch sides.'],
          formCues: ['Keep body in one plane — no rotation.','Squeeze glutes — prevents hip dropping.','Hips elevated throughout.','Raise top leg for difficulty.'],
          kalories: 4, muscles: ['Internal Oblique','External Oblique','Quadratus Lumborum'], previewEmoji: ''),
        Exercise(id: 'oblique_crunch', name: 'Oblique Crunch', muscleGroup: 'Obliques',
          difficulty: 'Beginner', equipment: 'None', durationSeconds: 40,
          sets: 3, reps: '15-20 per side', gifUrl: 'Oblique_Crunches_-_On_The_Floor',
          description: 'Rotates torso through trunk rotation against gravity, directly targeting external and internal obliques.',
          steps: ['Lie on back, knees bent, feet flat.','Left hand behind head, right arm extended.','Crunch up and rotate left elbow toward right knee.','Hold twist 1 second at top.','Lower slowly. Switch sides.'],
          formCues: ['Rotate from obliques not neck.','Do not let elbow flare.','Elbow and knee aim to meet.','2 seconds up, 2 seconds down.'],
          kalories: 4, muscles: ['External Oblique','Internal Oblique','Rectus Abdominis'], previewEmoji: ''),
        Exercise(id: 'hanging_oblique_raise', name: 'Hanging Oblique Raise', muscleGroup: 'Obliques',
          difficulty: 'Advanced', equipment: 'Pull-Up Bar', durationSeconds: 45,
          sets: 3, reps: '10-12 per side', gifUrl: 'Hanging_Leg_Raise',
          description: 'Most intense oblique stimulus possible, producing the V-cut oblique definition.',
          steps: ['Hang from bar, overhand grip, body straight.','Bring knees up toward chest.','At top, rotate knees to the right as far as possible.','Hold 1 second at peak rotation.','Lower slowly. Alternate sides.'],
          formCues: ['No swinging — core control.','Rotation is what makes this oblique exercise.','Hip should point toward ceiling at top.','Use straps if grip fails.'],
          kalories: 7, muscles: ['External Oblique','Internal Oblique','Hip Flexors'], previewEmoji: ''),
        Exercise(id: 'v_up', name: 'V-Up', muscleGroup: 'Obliques',
          difficulty: 'Intermediate', equipment: 'None', durationSeconds: 40,
          sets: 3, reps: '15-20', gifUrl: 'Bent-Knee_Hip_Raise',
          description: 'Combines hip flexion and trunk flexion challenging the entire anterior core simultaneously.',
          steps: ['Lie flat, arms extended overhead, legs straight.','Simultaneously raise legs and upper body, reaching hands toward toes.','Body forms V shape at top.','Lower back to start under control.','Do not let legs or upper body touch floor between reps.'],
          formCues: ['Reach for toes — not just raise arms.','Legs stay straight.','Control the lowering phase.','Bend knees as regression.'],
          kalories: 6, muscles: ['Rectus Abdominis','External Oblique','Hip Flexors'], previewEmoji: ''),
      ],
    ),

  ];

  static final List<WorkoutPreset> presets = [
    WorkoutPreset(id: 'adv_chest_tri', name: 'Advanced Chest & Triceps', level: 'Advanced', duration: '50-60 min', icon: 'fire', color: 0xFFEF5350, description: 'Compound pressing combined with tricep isolation — no machines required.', exerciseIds: ['push_up','incline_db_press','dumbbell_fly','chest_dip','skull_crusher','diamond_push_up']),
    WorkoutPreset(id: 'back_bis', name: 'Back & Biceps Blast', level: 'Intermediate', duration: '50-60 min', icon: 'blast', color: 0xFF42A5F5, description: 'Complete back development from width to thickness, finished with bicep work.', exerciseIds: ['pull_up','chin_up','bent_over_row','inverted_row','bicep_curl','hammer_curl','preacher_curl']),
    WorkoutPreset(id: 'leg_day', name: 'Leg Day Protocol', level: 'Intermediate', duration: '55-65 min', icon: 'legs', color: 0xFF66BB6A, description: 'Complete lower body — quads, hamstrings, glutes, and calves in one session.', exerciseIds: ['barbell_squat','deadlift','romanian_deadlift','lunges','glute_bridge','standing_calf_raise']),
    WorkoutPreset(id: 'full_body', name: 'Full Body Strength', level: 'Beginner', duration: '45 min', icon: 'power', color: 0xFFFFA726, description: 'Balanced full-body workout covering all major muscle groups. Perfect for 3x/week.', exerciseIds: ['push_up','pull_up','squat','lunges','plank','russian_twist']),
    WorkoutPreset(id: 'upper_body', name: 'Upper Body Power', level: 'Intermediate', duration: '55-65 min', icon: 'strength', color: 0xFFAB47BC, description: 'Comprehensive upper body hitting chest, back, shoulders, and arms.', exerciseIds: ['push_up','overhead_press','pull_up','bent_over_row','lateral_raise','bicep_curl','tricep_dip']),
    WorkoutPreset(id: 'core_blast', name: 'Core Blast', level: 'Beginner', duration: '20-30 min', icon: 'core', color: 0xFFEF9A9A, description: 'Targeted core circuit training all abdominal regions — upper, lower, and obliques.', exerciseIds: ['plank','crunches','leg_raise','mountain_climber','russian_twist','dead_bug']),
    WorkoutPreset(id: 'push_day', name: 'Push Day', level: 'Intermediate', duration: '55 min', icon: 'push', color: 0xFFFF7043, description: 'Classic Push day — chest, shoulders, and triceps for optimal pressing strength.', exerciseIds: ['push_up','incline_db_press','overhead_press','lateral_raise','chest_dip','skull_crusher']),
    WorkoutPreset(id: 'pull_day', name: 'Pull Day', level: 'Intermediate', duration: '55 min', icon: 'pull', color: 0xFF42A5F5, description: 'Classic Pull day — all pulling movements for the back and biceps.', exerciseIds: ['pull_up','chin_up','bent_over_row','inverted_row','rear_delt_fly','bicep_curl','hammer_curl']),
    WorkoutPreset(id: 'lower_body_power', name: 'Lower Body Power', level: 'Advanced', duration: '65-75 min', icon: 'lower', color: 0xFF66BB6A, description: 'Advanced lower body — deadlifts, squats, hip thrusts, and glute work.', exerciseIds: ['deadlift','barbell_squat','romanian_deadlift','hip_thrust','glute_bridge','standing_calf_raise']),
    WorkoutPreset(id: 'hiit_cardio', name: 'HIIT Cardio Blast', level: 'Intermediate', duration: '20-30 min', icon: 'fire', color: 0xFFFF7043, description: 'High-intensity interval training with explosive bodyweight exercises.', exerciseIds: ['burpees','high_knees','jumping_jacks','mountain_climber','box_jump','bear_crawl']),
    WorkoutPreset(id: 'arm_annihilator', name: 'Arm Annihilator', level: 'Intermediate', duration: '40-50 min', icon: 'strength', color: 0xFFFFA726, description: 'Dedicated arm session alternating bicep and tricep exercises for maximum pump.', exerciseIds: ['bicep_curl','skull_crusher','hammer_curl','diamond_push_up','preacher_curl','tricep_dip']),
    WorkoutPreset(id: 'glutes_hamstrings', name: 'Glutes & Hamstrings', level: 'Intermediate', duration: '45-55 min', icon: 'glutes', color: 0xFFEC407A, description: 'Posterior chain focus — glute strength and hamstring flexibility for performance.', exerciseIds: ['hip_thrust','sumo_squat','romanian_deadlift','glute_kickback','glute_bridge','single_leg_calf_raise']),
    WorkoutPreset(id: 'bodyweight_only', name: 'Zero Equipment Workout', level: 'Beginner', duration: '30-40 min', icon: 'bodyweight', color: 0xFF26C6DA, description: 'Complete full-body workout using only bodyweight — do it anywhere, anytime.', exerciseIds: ['push_up','squat','pull_up','lunges','plank','glute_bridge','mountain_climber','diamond_push_up']),
    WorkoutPreset(id: 'posterior_chain', name: 'Posterior Chain Master', level: 'Advanced', duration: '65-80 min', icon: 'posterior', color: 0xFF6D4C41, description: 'Complete posterior chain — lower back, hamstrings, and glutes in one session.', exerciseIds: ['deadlift','good_morning','hyperextension','nordic_curl','reverse_hyperextension','bird_dog']),
    WorkoutPreset(id: 'quad_destroyer', name: 'Quad Destroyer', level: 'Advanced', duration: '55-65 min', icon: 'quadriceps', color: 0xFF1E88E5, description: 'Maximum quad volume using compound and isolation movements.', exerciseIds: ['front_squat','bulgarian_split_squat','barbell_squat','sissy_squat','wall_sit','jump_squat']),
    WorkoutPreset(id: 'hamstring_focus', name: 'Hamstring Protocol', level: 'Intermediate', duration: '45-55 min', icon: 'legs', color: 0xFF00838F, description: 'Dedicated hamstring training using eccentric-focused exercises. Reduces injury risk.', exerciseIds: ['nordic_curl','romanian_deadlift_ham','glute_ham_bridge','swiss_ball_leg_curl','good_morning_ham','superman_hold']),
    WorkoutPreset(id: 'hip_stability', name: 'Hip & Adductor Strength', level: 'Beginner', duration: '30-40 min', icon: 'adductors', color: 0xFFD81B60, description: 'Functional hip stability targeting adductors and abductors — essential for knee health.', exerciseIds: ['lateral_lunge','copenhagen_plank','clamshell','lateral_band_walk','curtsy_lunge','monster_walk']),
    WorkoutPreset(id: 'complete_core', name: 'Complete Core Circuit', level: 'Intermediate', duration: '30-40 min', icon: 'obliques', color: 0xFFF4511E, description: 'All-planes core training covering rectus abdominis, obliques, and deep stabilisers.', exerciseIds: ['plank','side_plank','oblique_crunch','hanging_oblique_raise','dead_bug','russian_twist','v_up']),
    WorkoutPreset(id: 'athletic_performance', name: 'Athletic Performance', level: 'Advanced', duration: '55-65 min', icon: 'athletic', color: 0xFFFF6F00, description: 'Power, explosiveness, and injury prevention — trains what separates great athletes.', exerciseIds: ['box_jump','dragon_flag','nordic_curl','hanging_knee_raise','monster_walk','bird_dog','burpees']),
    WorkoutPreset(id: 'lower_back_rehab', name: 'Lower Back Strengthening', level: 'Beginner', duration: '25-35 min', icon: 'lower_back', color: 0xFF795548, description: 'Progressive lower back strengthening for injury prevention and rehabilitation.', exerciseIds: ['bird_dog','superman_hold','hyperextension','reverse_hyperextension','good_morning','dead_bug']),
    WorkoutPreset(id: 'shoulder_health', name: 'Shoulder Health & Stability', level: 'Beginner', duration: '30-40 min', icon: 'serratus', color: 0xFF43A047, description: 'Rotator cuff, serratus anterior, and rear deltoid work to build bulletproof shoulders.', exerciseIds: ['push_up_plus','serratus_punch','rear_delt_fly','y_t_w_raise','dumbbell_pullover','overhead_shrug']),
    WorkoutPreset(id: 'neck_trap_combo', name: 'Neck & Trap Builder', level: 'Intermediate', duration: '35-45 min', icon: 'neck', color: 0xFF546E7A, description: 'Combined neck and trapezius session for complete upper cervical development.', exerciseIds: ['barbell_shrug','neck_extension','neck_flexion','y_t_w_raise','neck_lateral_flexion','wrestlers_bridge']),
  ];

  static Exercise? findById(String id) {
    for (final g in muscleGroups) {
      for (final e in g.exercises) {
        if (e.id == id) return e;
      }
    }
    return null;
  }

  static List<Exercise> exercisesForPreset(WorkoutPreset preset) =>
      preset.exerciseIds.map((id) => findById(id)).whereType<Exercise>().toList();

  static List<String> get allExerciseIds =>
      muscleGroups.expand((g) => g.exercises.map((e) => e.id)).toList();
}
